import { StyleSheet } from "react-native"

export default styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: 'white',
        alignItems: 'center',
        //justifyContent: 'center',
        fontSize: 50,
        flexDirection: 'column',
    },
    textoTomada: {
        backgroundColor: 'white',
        margin: 20,
        padding: 5,
        width: 100,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 5,
    },
    tomadaCadastrada: {
        backgroundColor: '#c6c6c6',
        width: 350,
        padding: 10,
        alignItems: 'center',
        justifyContent: 'center',
        margin: 5,
        borderRadius: 5,
        flexDirection: 'row', 
    },
    tomadaCadastradaInfo: {
        backgroundColor: 'white',
        width: 200,
        padding: 10,
        alignItems: 'center',
        margin: 10,
        borderRadius: 5,
    },
    containerInfoTomada: {
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'column',
    },
    imagemTomada: {
        width: 15,
        padding: 15,
    },
    tomadaId: {
        alignItems: 'center',
        justifyContent: 'center',
        margin: 10,
    },
    botaoTomada: {
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 15,
    },
    botaoTomada1: {
        backgroundColor: 'red',
        margin: 5,
        padding: 5,
        width: 70,
        borderRadius: 5,
        alignItems: 'center',
        justifyContent: 'center',
        color: 'white',
    },
    botao_Tomada: {
        color: 'white',
        border: 5,
        backgroundColor: '#ACAAAD',
        padding: 25,
        width: 70,
        borderRadius: 100,
        marginTop: 50,
        marginLeft: 300,
        justifyContent: 'center',
        alignItems: 'center',
    },
});